Data_Preparation:
  test_size: 0.25
  random_state: 20

Train:
  Random_Forest:
    n_estimators: 372
    criterion: 'squared_error'
    max_depth: 30
    max_features: null
    min_samples_split: 7
    min_samples_leaf: 3
    max_samples: 0.5003890142288723
    verbose: 1
    n_jobs: -1
  
  LightGBM:
    n_estimators: 57
    max_depth: 18
    learning_rate: 0.11508843979525717
    subsample: 0.8219692257816482
    min_child_weight: 12
    min_split_gain: 0.1266801534144861
    reg_lambda: 70.7734573994436
    n_jobs: -1
